trigger:
- main  # Change this to your branch name

pr:
- main

jobs:
- job: BuildAndPush
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  # - task: Docker@2
  #   inputs:
  #     containerRegistry: ''
  #     repository: 'myapp'
  #     command: 'buildAndPush'
  #     Dockerfile: '**/Dockerfile'
  #     tags: '$(Build.BuildId)'
  - task: Docker@2
    inputs:
      containerRegistry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      repository: ${{ secrets.AZURE_CONTAINER_REPOSITORY }}
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
